# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0004_spaceplugin'),
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpacesWiki',
            fields=[
                ('spaceplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spaces.SpacePlugin')),
            ],
            bases=('spaces.spaceplugin',),
        ),
        migrations.CreateModel(
            name='WikiArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wiki.Article')),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces_wiki.SpacesWiki')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
    ]
